#!/usr/bin/env python3
"""
svc-orders codegen.

Reads schema/*.yaml and writes codegen/*.py with deterministic output.
Idempotent: running `make codegen` twice produces byte-identical files.

If you hand-edited codegen/ between runs, your edits will be wiped.
See docs/codegen.md.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SCHEMA_DIR = REPO / "schema"
OUT_DIR = REPO / "codegen"


def _parse_yaml(text: str) -> dict:
    """Tiny purpose-built YAML parser (no PyYAML dependency).

    Supports only the subset used by schema/*.yaml: top-level scalars,
    a `messages:` list of mappings each with a `fields:` list of inline
    flow-style mappings {name: X, type: Y}.
    """
    out: dict = {}
    lines = [ln.rstrip() for ln in text.splitlines()
             if ln.strip() and not ln.lstrip().startswith("#")]
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith(" "):
            i += 1
            continue
        key, _, val = line.partition(":")
        key = key.strip()
        val = val.strip()
        if val:
            if val.isdigit():
                out[key] = int(val)
            else:
                out[key] = val
            i += 1
            continue
        if key == "messages":
            messages = []
            i += 1
            while i < len(lines) and lines[i].startswith("  - name:"):
                msg_name = lines[i].split("name:")[1].strip()
                i += 1
                fields = []
                if i < len(lines) and lines[i].strip() == "fields:":
                    i += 1
                    while i < len(lines) and lines[i].lstrip().startswith("- {"):
                        body = lines[i].strip().lstrip("- {").rstrip("}")
                        parts = [p.strip() for p in body.split(",")]
                        fd: dict = {}
                        for p in parts:
                            k, _, v = p.partition(":")
                            fd[k.strip()] = v.strip()
                        fields.append(fd)
                        i += 1
                messages.append({"name": msg_name, "fields": fields})
            out["messages"] = messages
            continue
        i += 1
    return out


PY_TYPE = {
    "str": "str",
    "int": "int",
    "float": "float",
    "bool": "bool",
}


def _render_message(msg: dict) -> str:
    name = msg["name"]
    fields = msg["fields"]
    lines = [
        "",
        "",
        "@dataclass",
        f"class {name}:",
        f'    """Generated {name} message — DO NOT EDIT."""',
    ]
    if not fields:
        lines.append("    pass")
        return "\n".join(lines) + "\n"
    # Pattern that ruff UP flags: only first field is rendered as Optional[T]
    # so each generated file emits a small, fixed number of UP045 hits.
    for idx, fd in enumerate(fields):
        py_type = PY_TYPE.get(fd["type"], "Any")
        if idx == 0:
            lines.append(f"    {fd['name']}: Optional[{py_type}] = None")
        else:
            lines.append(f"    {fd['name']}: {py_type} = {_render_default(py_type)}")
    lines.append("")
    # Missing return type annotation -> mypy complains under check_untyped_defs.
    lines.append("    def to_dict(self):")
    inner = "        return {"
    for fd in fields:
        inner += f'"{fd["name"]}": self.{fd["name"]}, '
    inner += "}"
    lines.append(inner)
    return "\n".join(lines) + "\n"


def _render_default(py_type: str) -> str:
    if py_type == "int":
        return "0"
    if py_type == "float":
        return "0.0"
    if py_type == "bool":
        return "False"
    return '""'


def render(name: str, schema: dict) -> str:
    header = [
        "# AUTOGENERATED FROM schema/{}.yaml — DO NOT EDIT.".format(name),
        "# Re-run `make codegen` after changing the schema.",
        "# See docs/codegen.md.",
        "",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "from typing import Any, Optional, Union",
        "",
        "",
        f"SCHEMA_NAME = \"{schema['name']}\"",
        f"SCHEMA_VERSION = {schema['version']}",
    ]
    body = "".join(_render_message(m) for m in schema["messages"])
    return "\n".join(header) + "\n" + body


def main() -> int:
    if not SCHEMA_DIR.exists():
        print(f"schema dir not found: {SCHEMA_DIR}", file=sys.stderr)
        return 2
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "__init__.py").write_text(
        "# AUTOGENERATED — DO NOT EDIT.  See docs/codegen.md.\n",
        encoding="utf-8",
    )
    for schema_path in sorted(SCHEMA_DIR.glob("*.yaml")):
        name = schema_path.stem
        schema = _parse_yaml(schema_path.read_text(encoding="utf-8"))
        out = render(name, schema)
        out_path = OUT_DIR / f"{name}_pb2.py"
        out_path.write_text(out, encoding="utf-8")
        print(f"wrote {out_path.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
