# AUTOGENERATED FROM schema/orders.yaml — DO NOT EDIT.
# Re-run `make codegen` after changing the schema.
# See docs/codegen.md.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Optional, Union


SCHEMA_NAME = "orders"
SCHEMA_VERSION = 3


@dataclass
class OrderHeader:
    """Generated OrderHeader message — DO NOT EDIT."""
    order_id: Optional[str] = None
    customer_id: int = 0
    created_at: str = ""
    status: str = ""

    def to_dict(self):
        return {"order_id": self.order_id, "customer_id": self.customer_id, "created_at": self.created_at, "status": self.status, }


@dataclass
class OrderLine:
    """Generated OrderLine message — DO NOT EDIT."""
    line_id: Optional[str] = None
    sku: str = ""
    quantity: int = 0
    unit_price: float = 0.0

    def to_dict(self):
        return {"line_id": self.line_id, "sku": self.sku, "quantity": self.quantity, "unit_price": self.unit_price, }


@dataclass
class OrderRefund:
    """Generated OrderRefund message — DO NOT EDIT."""
    refund_id: Optional[str] = None
    order_id: str = ""
    amount: float = 0.0
    reason: str = ""

    def to_dict(self):
        return {"refund_id": self.refund_id, "order_id": self.order_id, "amount": self.amount, "reason": self.reason, }
