# AUTOGENERATED FROM schema/payments.yaml — DO NOT EDIT.
# Re-run `make codegen` after changing the schema.
# See docs/codegen.md.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Optional, Union


SCHEMA_NAME = "payments"
SCHEMA_VERSION = 4


@dataclass
class PaymentMethod:
    """Generated PaymentMethod message — DO NOT EDIT."""
    method_id: Optional[str] = None
    kind: str = ""
    last4: str = ""

    def to_dict(self):
        return {"method_id": self.method_id, "kind": self.kind, "last4": self.last4, }


@dataclass
class PaymentReceipt:
    """Generated PaymentReceipt message — DO NOT EDIT."""
    receipt_id: Optional[str] = None
    order_id: str = ""
    amount: float = 0.0
    method_id: str = ""

    def to_dict(self):
        return {"receipt_id": self.receipt_id, "order_id": self.order_id, "amount": self.amount, "method_id": self.method_id, }
