# AUTOGENERATED FROM schema/users.yaml — DO NOT EDIT.
# Re-run `make codegen` after changing the schema.
# See docs/codegen.md.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Optional, Union


SCHEMA_NAME = "users"
SCHEMA_VERSION = 2


@dataclass
class UserRecord:
    """Generated UserRecord message — DO NOT EDIT."""
    user_id: Optional[int] = None
    email: str = ""
    display_name: str = ""

    def to_dict(self):
        return {"user_id": self.user_id, "email": self.email, "display_name": self.display_name, }


@dataclass
class UserAddress:
    """Generated UserAddress message — DO NOT EDIT."""
    address_id: Optional[int] = None
    user_id: int = 0
    line1: str = ""
    city: str = ""
    country: str = ""

    def to_dict(self):
        return {"address_id": self.address_id, "user_id": self.user_id, "line1": self.line1, "city": self.city, "country": self.country, }
